# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김유안
title: 프론트엔드 개발자
email: mini5621@gmail.com
website: https://github.com/yxxax
blog: https://dev-you.tistory.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: yxxax
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: Blog
    icon: fas fa-globe
    url: https://dev-you.tistory.com
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Introduce
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  2년차 웹개발자 김유안입니다. 현대실용음악을 전공하면서 음악 프로그램(미디)을 다루던 중 예상치 못한 오류를 해결하는 과정에서 느낀 성취감이 저를 개발이라는 새로운 길로 이끌었습니다.
  현재는 React, Next.js 등 최신 프레임워크를 활용하여 사용자 경험(UX)을 향상시키는 프론트엔드 개발자로 성장하고 있습니다.
  특히, 개발과 디자인의 접점에서 사용자 중심의 인터페이스를 만들어내는 과정에 깊이 흥미를 느끼고 있습니다.
  UI/UX 개선과 코드의 유지보수성을 중요하게 생각하며, 협업과 효율적인 코드 작성에 집중하고 있습니다.
  앞으로도 사용자 중심의 인터페이스를 고민하고 구현하며, 변화하는 기술을 탐구하는 개발자로 성장해 나가겠습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 베러웨이시스템즈
        # link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Front-End Developer
        caption: 2023.06 - 현재
        description: | # this will include new lines to allow paragraphs
          <h2 style="color: #333333; font-weight: bold;">오픈마켓 파일 편집페이지</h2>
          <a href="https://podbridge.co.kr/" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            https://podbridge.co.kr/</a>

            **Tech Stack**
            - Next.js
            - React.js
            - Typescript
            - Recoil
            - NextAuth

            **Description**

            네이버, 쿠팡, 11번가 등의 오픈마켓에서 구매한 상품을 카카오톡 링크를 통해 파일을 편집하고 업로드할 수 있는 레드프린팅 서비스 개발에 참여했습니다.
            이 프로젝트에서는 Next.js 기반의 SSR(서버 사이드 렌더링)을 적용하여 성능을 개선하고, SEO 최적화를 진행했으며, 사용자 인증 및 세션 관리를 담당했습니다.
            특히, NextAuth를 활용하여 일반 로그인, 함께하기 로그인, 게스트 로그인 기능을 구현하여, 초대받은 사용자도 인증 후 주문 및 편집이 가능하도록 개발했습니다.
            또한, 신규 사용자가 서비스를 더욱 쉽게 이용할 수 있도록 튜토리얼 기능을 개발하여 UX를 개선하는 작업도 수행했습니다.
            이 과정에서 닉네임, 공유 코드, 전화번호 값 등의 사용자 정보를 세션에서 관리하도록 설계하였으며, Next.js, TypeScript, Recoil 등의 기술을 적극적으로 활용하며 프로젝트를 개발하는데 기여했습니다.

            **관련 상세**
            <a href="https://tattered-swan-746.notion.site/19e3338acb8980e59101ca0ea35a35fe?pvs=4" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            상세 내용 확인</a>
            <a href="https://youtu.be/r-AHey8QtzA" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            영상</a>

          ---

          <h2 style="color: #333333; font-weight: bold;">플랫폼 백오피스 마이그레이션</h2>
          <a href="https://platform-manager.betterwaysys.com/" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            https://platform-manager.betterwaysys.com/</a>

            **Tech Stack**
            - Next.js
            - React.js
            - Typescript
            - Recoil
            - React Query
            - Mongoose
            - NextAuth
            - Turbo (Monorepo)
            - Ant Design

            **Description**

            직원 전용 백오피스 시스템의 유지보수성과 성능을 개선하기 위해 Meteor 기반의 Full-stack 환경을 Next.js 기반으로 마이그레이션하였습니다.
            이 과정에서 Server Side Rendering(SSR) 및 Static Site Generation(SSG)을 적용하여 성능을 최적화하고 SEO를 강화하였으며, UI/UX 측면에서도 불필요한 복잡성을 줄이고 사용성을 개선하는 작업을 진행하였습니다.
            또한, 기존에 사용하던 styled-components 및 stitches를 제거하고 Ant Design과 TailwindCSS를 적용하여 스타일 아키텍처를 개선하고, UI 구성 방식을 체계적으로 정리하였습니다.
            pnpm workspace를 도입하여 모노레포 환경을 구축함으로써 프로젝트 관리 효율성을 높이고, 패키지 의존성을 효과적으로 관리할 수 있도록 구성하였습니다.
            이번 마이그레이션을 통해 상품 관리, Custom CSS 관리, 커스텀 상품 S3 관리, 위젯 S3 관리, 정산 관리, 재주문 관리 페이지 등의 주요 기능을 새로운 환경에서 원활하게 운영할 수 있도록 하였으며, 코드의 유지보수성과 확장성을 고려한 구조로 개선하였습니다.

            **관련 상세**
            <a href="https://tattered-swan-746.notion.site/1a23338acb8980e88856f02425a848e0?pvs=4" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            상세 내용 확인</a>
            <a href="https://youtu.be/STQVqPH5dTo" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            영상</a>

          ---

          <h2 style="color: #333333; font-weight: bold;">청첩장 사이트 잇츠카드 백오피스</h2>

            **Tech Stack**
            - Next.js
            - React.js
            - Typescript
            - Recoil
            - Tailwind
            - Ant Design

            **Description**

            청첩장 사이트인 잇츠카드에서 사용되는 제품들을 관리하는 잇츠카드 백오피스 프로젝트를 진행했습니다. 
            기존 청첩장 사이트는 백오피스 시스템 없이 구형 ERP 프로그램을 통해 생산 코드를 직접 입력하고 관리해야 했습니다.
            이로 인해 기획 및 디자인 팀이 특정 환경에서만 작업할 수 있어 운영상의 비효율성이 존재했고, 사이트 내 이벤트 및 프로모션 콘텐츠 수정도 개발자가 직접 반영해야 하는 구조여서 신속한 업데이트가 어려웠습니다.
            이러한 문제를 해결하고 기획 및 디자인 팀이 독립적으로 데이터를 관리할 수 있도록 백오피스 시스템 구축 프로젝트에 참여했습니다.
            Next.js 및 Ant Design UI를 활용하여 메뉴 설정, 공지사항, FAQ, 이벤트 및 어드민 계정 관리 기능을 개발했으며, 이를 통해 기획 및 디자인팀이 개발자의 도움 없이도 주요 기능을 손쉽게 수정하고 관리할 수 있도록 개선했습니다. 
            이로써, Next.js와 Ant Design UI를 활용한 백오피스 시스템 구축을 통해 대규모 데이터 관리 및 UI/UX 개선 경험을 쌓을 수 있었습니다.

            **관련 상세**
            <a href="https://tattered-swan-746.notion.site/1a33338acb8980c9962dfa1f349eb261?pvs=4" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            상세 내용 확인</a>

          ---

           <h2 style="color: #333333; font-weight: bold;">플랫폼 웹앱</h2>
           <a href="https://platform-manager.betterwaysys.com/" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            https://platform-manager.betterwaysys.com/</a>

            **Tech Stack**
            - Next.js
            - React.js
            - Typescript
            - Recoil
            - Tailwind
            - Stitches

            **Description**

            소비자가 상품을 커스텀하여 주문할 수 있는 기존 위젯을 기반으로 기능을 확장하고, 이를 타업체에서도 활용할 수 있도록 빌더 기능을 포함한 SDK 형태로 제공하는 플랫폼 웹앱의 관리 및 기능 추가, 상품 생성 및 배포 스크립트 작성에 참여했습니다.

            **관련 상세**
            <a href="https://tattered-swan-746.notion.site/1a33338acb898052a81ec3b81117e83a?pvs=4" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            상세 내용 확인</a>
            <a href="https://youtu.be/DEiW7aNPSnc" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            영상</a>

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Popcorn project
        caption: 2023.01 - 2023.02
        sub_title: 다양한 팝업스토어의 정보들을 한 곳에서 볼 수 있으며, 주변 음식점과 카페까지 추천해주는 웹사이트
        link: github.com/heerachoi/popcorn
        description: | # this will include new lines to allow paragraphs
          **Tech Stack**
            - JavaScript
            - TypeScript
            - React.js
            - React Query
            - Recoil
            - Axios
            - Styled-component
            - Firebase
            - JSON-Server

          **Description**

          - 프로필 닉네임, 이미지 수정 기능 구현
          - axios를 사용하여 JSON-Server에서 북마크 추가, 삭제 기능 구현
          - Kakao API와 OAuth2.0을 이용한 소셜 로그인, 로그아웃 기능 구현, 카카오 로그인 상태 전역 관리

          **관련 상세**
          <a href="https://youtu.be/v80lrAb66h0" style="display:flex; font-style:italic; text-align:center; font-size: 14px; color: #888;">
            발표 영상</a>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 스파르타 내일배움캠프
        caption: 2022.10 - 2023.03
        sub_title: 리액트 4기
        description: | # this will include new lines to allow paragraphs
          비전공자를 위한 프론트엔드 개발자 양성 과정을 5개월 간 수료하였습니다. 
          HTML/CSS 기초부터 시작해 JavaScript 및 React를 활용한 SPA 개발을 학습하였으며, 4번의 팀 프로젝트를 통해 Git을 활용한 협업과 코드 관리 경험을 쌓았습니다.

          OAuth를 활용한 인증 시스템을 구현하였으며, Firebase를 사용하여 데이터 CRUD 기능을 적용하였습니다.
          134일의 캠프 기간 동안 155개의 글을 기술 블로그를 작성하였으며, 이론 공부와 함께 78일의 잔디를 심었습니다. 또한, 4번의 팀 프로젝트 중 2번의 발표를 진행하여, 프로젝트를 효과적으로 표현하고 협업 능력을 키울 수 있었습니다.
      - layout: left
        title: 성신여자대학교
        caption: 2019.03 - 2022.02
        sub_title: 현대실용음악학과 학사
        description: | # this will include new lines to allow paragraphs
          대학에 다니면서 내가 하고자하는 분야에서 인정받기 위해 꾸준히 노력한 결과, 평균 4점 대의 학점을 유지했습니다. 또한 더 넓은 세상을 보기 위해 어학 연수 장학생으로 선발되어 1달 간의 아일랜드 어학 연수를 다녀온 경험이 있습니다.
          이런 끈기와 성실함을 발판삼아 부트 캠프 기간과 프론트엔드 개발자로서 끊임없이 공부하며 성장했습니다.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Workout & Stretching
      - Collecting stationery
      - Watching Animation

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

livereload: true
incremental: true
force_polling: true
